#!/bin/bash
TARGET="/web/frontend"
GIT_DIR="/home/git/frontend.git"
BRANCH="master"

while read oldrev newrev ref
do
        if [ "$ref" = "refs/heads/$BRANCH" ];
        then
                echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
                git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH

                cd $TARGET 
                docker-compose down
                docker volume rm web_build_folder
                docker-compose up -d --build
                yes | docker system prune

                echo "Successfully deployed frontend!"
        else                                                                                                     
                echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
        fi
done
